name: Bing_Wallpaper_Download

on:
  # Runs the workflow every day at 00:01 KST (15:01 UTC)
  schedule:
    - cron: "1 15 * * *"
  workflow_dispatch:

jobs:
  play:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Run Project
        run: npm run start
      - name: Commit files
        run: |
          git config --local user.email "exposir@foxmail.com"
          git config --local user.name "exposir"
          git pull
          git add ./
          git commit -m "update wallpaper"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_GIT_TOKEN }}
          branch: main
